### ISSUE TITLE
RuntimeError: Empty or `None` reference sentence found

### ISSUE THREAD

**Issue by HammerWang98** [hemingkx/ChineseNMT#10]
您好，运行完第一个epoch之后，第二个epoch就报错，没有tgt sentence，是生成的语料没有对齐吗。如何解决

**Comment by HammerWang98** [comment]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 395/395 [38:25<00:00,  5.84s/it]
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    run()
  File "main.py", line 78, in run
    train(train_dataloader, dev_dataloader, model, model_par, criterion, optimizer)
  File "/root/ChineseNMT/train.py", line 43, in train
    bleu_score = evaluate(dev_data, model)
  File "/root/ChineseNMT/train.py", line 170, in evaluate
    bleu = sacrebleu.corpus_bleu(res, trg, tokenize='zh')
  File "/root/miniconda3/lib/python3.8/site-packages/sacrebleu/compat.py", line 35, in corpus_bleu
    return metric.corpus_score(hypotheses, references)
  File "/root/miniconda3/lib/python3.8/site-packages/sacrebleu/metrics/base.py", line 421, in corpus_score
    stats = self._extract_corpus_statistics(hypotheses, references)
  File "/root/miniconda3/lib/python3.8/site-packages/sacrebleu/metrics/base.py", line 366, in _extract_corpus_statistics
    ref_cache = self._cache_references(references)
  File "/root/miniconda3/lib/python3.8/site-packages/sacrebleu/metrics/base.py", line 333, in _cache_references
    raise RuntimeError("Empty or `None` reference sentence found.")
RuntimeError: Empty or `None` reference sentence found.

**Comment by liminn** [comment]
same error

**Comment by HammerWang98** [comment]
> same error

I had solved it.
change your method to install sacrebleu rather than pip.

**Comment by liminn** [comment]
> > same error
> 
> I had solved it. change your method to install sacrebleu rather than pip.

you are linux or windows?

**Comment by liminn** [comment]
> > same error
> 
> I had solved it. change your method to install sacrebleu rather than pip.

I can't solve this error by your method.

**Comment by wangdf90** [comment]
> 

how do you solve this error？ @HammerWang98

**Comment by wangdf90** [comment]
pip install sacrebleu==1.4.14 
@liminn @HammerWang98
